/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalMathDslParser;
import org.xtext.example.mydsl.services.MathDslGrammarAccess;

public class MathDslParser extends AbstractAntlrParser {

	@Inject
	private MathDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMathDslParser createParser(XtextTokenStream stream) {
		return new InternalMathDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AllExp";
	}

	public MathDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MathDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
