/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.MathDslRuntimeModule;
import org.xtext.example.mydsl.MathDslStandaloneSetup;
import org.xtext.example.mydsl.ide.MathDslIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MathDslIdeSetup extends MathDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    MathDslRuntimeModule _mathDslRuntimeModule = new MathDslRuntimeModule();
    MathDslIdeModule _mathDslIdeModule = new MathDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_mathDslRuntimeModule, _mathDslIdeModule));
  }
}
