/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import jafre13.mathdsl.ui.internal.MathdslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MathDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MathdslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MathdslActivator.getInstance().getInjector(MathdslActivator.ORG_XTEXT_EXAMPLE_MYDSL_MATHDSL);
	}
	
}
