/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import jafre13.mathdsl.ui.internal.MathdslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MathDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MathdslActivator.getInstance().getInjector("org.xtext.example.mydsl.MathDsl");
	}

}
