/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.mathDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Raw Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mathDsl.RawVariable#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.mathDsl.MathDslPackage#getRawVariable()
 * @model
 * @generated
 */
public interface RawVariable extends Expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' reference.
   * @see #setValue(MathExp)
   * @see org.xtext.example.mydsl.mathDsl.MathDslPackage#getRawVariable_Value()
   * @model
   * @generated
   */
  MathExp getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mathDsl.RawVariable#getValue <em>Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' reference.
   * @see #getValue()
   * @generated
   */
  void setValue(MathExp value);

} // RawVariable
